export const iconList = [
  "Accessibility",
  "Baby",
  "Activity",
  "Award",
  "Briefcase",
  "Badge",
  "Sun",
  "Speech",
  "Moon",
  "Info",
  "Flag",
  "Cookie",
  "Contact",
  "Cog",
  "Cake",
  "Building",
  // "card",
  // "cards",
  // "check-square",
  // "clipboard-check",
  // "clipboard-list",
  // "contact-card",
  // "credit-card-check",
  // "credit-card-edit",
  // "credit-card-plus",
  // "credit-card-search",
  // "credit-card-x",
  // "credit-card",
  // "euro-circle",
  // "euro-square",
  // "euro",
  // "file-check",
  // "file-clock",
  // "file-cross",
  // "file-edit",
  // "file-heart",
  // "file-minus",
  // "file-plus",
  // "file-shield",
  // "file-star",
  // "file-user",
  // "file-x",
  // "file",
  // "files",
  // "fingerprint",
  // "folder-check",
  // "folder-clock",
  // "folder-cross",
  // "folder-edit",
  // "folder-heart",
  // "folder-minus",
  // "folder-plus",
  // "folder-shield",
  // "folder-star",
  // "folder-user",
  // "folder-x",
  // "folder",
  // "folders",
  // "group",
  // "key",
  // "lock-closed",
  // "lock-open",
  // "lock",
  // "mail-check",
  // "mail-clock",
  // "mail-cross",
  // "mail-heart",
  // "mail-minus",
  // "mail-plus",
  // "mail-search",
  // "mail-star",
  // "mail-user",
  // "mail-x",
  // "mail",
  // "message-check",
  // "message-cross",
  // "message-minus",
  // "message-plus",
  // "message-search",
  // "message-star",
  // "message-user",
  // "message-x",
  // "message",
  // "messages",
  // "mobile-check",
  // "mobile-cross",
  // "mobile-minus",
  // "mobile-plus",
  // "mobile-star",
  // "mobile-user",
  // "mobile-x",
  // "mobile",
  // "monitor-check",
  // "monitor-cross",
  // "monitor-minus",
  // "monitor-plus",
  // "monitor-star",
  // "monitor-user",
  // "monitor-x",
  // "monitor",
  // "profile",
  // "shield-check",
  // "shield-cross",
  // "shield-minus",
  // "shield-plus",
  // "shield-user",
  // "shield-x",
  // "shield",
  // "sign-in-alt",
  // "sign-in",
  // "sign-out-alt",
  // "sign-out",
  // "user-check",
  // "user-circle",
  // "user-clock",
  // "user-cross",
  // "user-edit",
  // "user-heart",
  // "user-minus",
  // "user-plus",
  // "user-search",
  // "user-shield",
  // "user-star",
  // "user",
  // "users-alt",
  // "users",
];
